# Generated by Django 6.0.3 on 2026-03-31 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='record',
            table='record_table',
        ),
    ]
