# Generated by Django 6.0.3 on 2026-03-31 12:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_record_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
