# Generated by Django 6.0.3 on 2026-04-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_record_issue_date'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('email', 'phone'), name='unique_email_phone'),
        ),
    ]
