# Generated by Django 6.0.3 on 2026-04-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_unique_email_phone'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_email_phone',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_email'),
        ),
    ]
